services:
  postgres:
    image: postgres:alpine
    container_name: course-work-postgres
    ports:
      - "5432:5432"  # Прокидаємо порт: зліва (Windows/WSL) -> справа (всередині контейнера)
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: course_work_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Щоб дані не зникали після перезапуску


  server:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: course-work-server
    ports:
      - "1323:1323"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/course_work_db
    depends_on:
      - postgres

volumes:
  postgres_data: